[tools]
bun = "latest"
node = "latest"
"npm:npkill" = "latest"
pnpm = "latest"
"npm:@github/copilot" = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:@playwright/cli" = "latest"
actionlint = "latest"
herdr = "latest"
"aqua:fullstorydev/grpcurl" = "latest"
"npm:druk" = "latest"
chezmoi = "latest"
hunk = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
